event: 2025mnros
scouters:
  - Mentor Zorm
  - Coach Ananda
  - Cassius Porter
  - Quinn Nguyen Hammel
  - Colten Kiehne
  - Aaron M
  - Michael M
  - James Hendrickson 
  - Luke Unterholzner
  - max miller
  - Anton Gakh
  - Eric M Roforth
  - Andrew schardt 
  - Collin Litzinger
  - Hunter lanza
  - Carly Thompson
  - Vinita Phord-Toy
  - Xiaoyan Ye
  - Tim Alexander
  - arden
  - Purity Ongeri
  - Lorelei Riska 
  - Maureen Riska 
  - Leo Aelony
  - Jay
  - Simon
  - Zack fernholz 
  - Zachary, White 
  - Ransom Woodrough
  - Sarah Peterson
  - Levi Lahr
  - Brian Bartholmai
  - Pranay Thapa
  - Pranya Thapa
  - Yi Guo
  - Matilde Cabrera 
  - Julia Logelin
  - Alan Czarnecki
  - Guest (lateformer)